### ISSUE TITLE
Unable to connect to PostgreSQL Database

### ISSUE THREAD

**Issue by b00walk3r** [raksdewji/free-games-discord-bot#5]
![image](https://user-images.githubusercontent.com/75166272/122676214-c05d7b80-d1e5-11eb-850c-dcb1dfa695dd.png)

**Comment by raksdewji** [comment]
Hey! First off, thanks for checking out my bot. 

So the issue you're having is when you run the bot locally, you need two things:
1. Discord Bot Key, this can obtained from [Discord Developer Portal](https://discord.com/developers/docs/intro)
2. PostgreSQL Database, for this I am using Heroku to host what the bot is using but you can use any service you like if you want to try running the bot locally. 

Here is where you can input your own PostgreSQL database config (sql.js)
![image](https://user-images.githubusercontent.com/18670250/122684631-b62a8580-d1c3-11eb-8ff0-1e78d19da441.png)


Once you input your own database credentials and config, you will be able to run the bot locally. 

Let me know if you have anymore questions! Thanks 😄

**Comment by b00walk3r** [comment]
Thanks for be interested :)
